Java M2M: enable Jackson BigDecimal option if model contains Decimal …
finos/legend-pure pull request #299
Opened 2021-08-17 11:28 UTC by aziemchawdhary-gs

Enable Jackson option to use BigDecimal for float values in M2M code generation.
Tests will be added to legend-engine as Pure JSON deserializer incorrectly deserializes large BigDecimal values

2021-08-18 13:31 UTC, dave-wathen approved these changes
Changes look good to me

2021-08-19 03:21 UTC, pierredebelen requested changes
To avoid confusion, could we translate the Pure Decimal type (fixed point) to BigDecimal?

2021-08-19 13:20 UTC, aziemchawdhary-gs commented
> To avoid confusion, could we translate the Pure Decimal type (fixed point) to BigDecimal?

We do use BigDecimal for PURE's Decimal.  This change ensures Jackson internally parses properly when we use them.

2021-08-19 13:31 UTC, pierredebelen commented
So what does useBigDecimalForFloats mean?

2021-08-19 13:37 UTC, aziemchawdhary-gs commented
sorry - where do you see that? I can't see that in my change - I did have that when I was prototyping the fix, so I may have inadvertently added that.

2021-08-19 13:38 UTC, aziemchawdhary-gs commented
> So what does useBigDecimalForFloats mean?

ah I see it - that parameter could be named better I guess

2021-08-19 13:39 UTC, aziemchawdhary-gs commented
That flag is used to set the parsing option in Jackson - in Jackson the flag is called USE_BIG_DECIMAL_FOR_FLOATS

2021-08-19 13:45 UTC, pierredebelen approved these changes

2021-08-19 13:45 UTC, merged